#ifndef COSTANTI_H
#define COSTANTI_H

#define TIPO_STRINGA 0
#define TIPO_INT 1
#define TIPO_FLOAT 2
#define TIPO_VETTORE 3
#define TIPO_MATRICE 4

#define MILLISECONDI 20
// AGGIORNARE MANO A MANO CHE SI AGGIUNGONO ALTRE TIPOLOGIE
// SERVE PER IL SALVATAGGIO PER IL FILE BINARIO

#endif
